server:
    port: 8081
    servlet:
        encoding:
            enabled: true
            force: true
            charset: UTF-8
spring:
    mvc:
        static-path-pattern=/static/**:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    datasource:
        name: mysql
        url: jdbc:mysql://127.0.0.1:3306/t_asset?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: root



#该配置节点为独立的节点，注意不要将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
    mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.javaee.lqsx.asset.po  #注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

#自定义上传路径
fileUpload: D:/upload

#阿里云服务
aliyun:
    oss:
        endpoint: https://oss-cn-hangzhou.aliyuncs.com
        accessKeyId: LTAI5tFBe2a4cot4jqC4QpNA
        accessKeySecret: ntHNLAtB0LK7yQG7sguFd04yuy082O
        bucketName: itwei-web-tlias